global:
  scrape_interval:     5s
  evaluation_interval: 5s


scrape_configs:
  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['localhost:8084']
        labels:
          application: 'Product Service Application'