global:
  scrape_interval:     10s
  evaluation_interval: 10s


scrape_configs:
  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.0.105:8084']
        labels:
          application: 'Product Service Application'
  - job_name: 'order_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.0.105:8081']
        labels:
          application: 'Order Service Application'
  - job_name: 'inventory_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.0.105:8082' ]
        labels:
          application: 'Inventory Service Application'
