
INSERT INTO inventory (SKU_CODE, QUANTITY) VALUES ('Iphone14_black_128G', 100);
INSERT INTO inventory (SKU_CODE, QUANTITY) VALUES ('Iphone14_white_128G', 100);
INSERT INTO inventory (SKU_CODE, QUANTITY) VALUES ('Iphone14_black_256G', 100);
INSERT INTO inventory (SKU_CODE, QUANTITY) VALUES ('Iphone14_white_256G', 100);
INSERT INTO inventory (SKU_CODE, QUANTITY) VALUES ('Iphone14_black_512G', 100);
INSERT INTO inventory (SKU_CODE, QUANTITY) VALUES ('Iphone14_white_512G', 100);
INSERT INTO inventory (SKU_CODE, QUANTITY) VALUES ('Iphone14PLUS_black_128G', 100);
INSERT INTO inventory (SKU_CODE, QUANTITY) VALUES ('Iphone14PLUS_white_128G', 100);
INSERT INTO inventory (SKU_CODE, QUANTITY) VALUES ('Iphone14PLUS_black_256G', 100);
INSERT INTO inventory (SKU_CODE, QUANTITY) VALUES ('Iphone14PLUS_white_256G', 100);
INSERT INTO inventory (SKU_CODE, QUANTITY) VALUES ('Iphone14PLUS_black_512G', 100);
INSERT INTO inventory (SKU_CODE, QUANTITY) VALUES ('Iphone14PLUS_white_512G', 100);